# Site settings
title: Nelly Garcia
email: nellyvags@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Research scientist specializing in sound synthesis and optimization of sound design"
keywords: "your keywords, separated by commas"
skills: "Audio Researcher - Sound Designer - Engineer in communications and electronics"
meta_author: Garcia Nelly

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: D59BF6 # Replace with your main color
  primary-rgb: "213,155,246" # RGB equivalent of D59BF6
  secondary: 60197D # Optional: pick a complementary color or another hex value
  secondary-dark: 330A4B # Optional: darker shade of the secondary color


# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: github
    url: http://github.com/nellyngz95

# Postal address (add as many lines as necessary)
address:
  - line: London, UK.

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
